### ISSUE TITLE
Criteria for taps-aff

### ISSUE THREAD

**Issue by lesbaa** [ColinWaddell/TapsAff-Django#1]
Here pal, how warm duz it huv tae be tae take ma tap aff?

**Comment by ColinWaddell** [comment]
Reet.

Here's the code that figures it out: https://github.com/ColinWaddell/TapsAff-Django/blob/master/www/taps/forecast.py#L73

Currently it's set to 17&deg;C (including windchill)

**Comment by lesbaa** [comment]
yaldi, ta

**Comment by ColinWaddell** [comment]
To anyone interested the new answer is, it's complicated 🤷‍♂️ 

<img width="1359" alt="screen shot 2018-04-18 at 22 25 36" src="https://user-images.githubusercontent.com/1848325/38959179-93e21ebe-4357-11e8-99be-2debcf4c7c4f.png">
